test
Signed-off-by: tao.yang <tao.yang@daocloud.io>

diff --git a/.github/workflows/auto-cherrypick.yaml b/.github/workflows/auto-cherrypick.yaml
--- a/.github/workflows/auto-cherrypick.yaml
+++ b/.github/workflows/auto-cherrypick.yaml
@@ -33,10 +33,163 @@ jobs:
         with:
           fetch-depth: 0
       
-      - name: echo
-        id: echo
+      - name: cherry pick
+        id: cherry-pick
+        env:
+          GITHUB_TOKEN: ${{ secrets.WELAN_PAT }}
+          JSON: ${{ toJSON(github) }}
         run: |
-          echo 123456 > robot.txt
+          set -x
+          echo "============ print var ======== "
+          if ${{ github.event_name == 'workflow_dispatch' }}; then
+                PR_NUMBER=${{ github.event.inputs.prNumber }}
+          else
+                grep -Eio "Merge pull request #[0-9]+ " <<< "${JSON}" || true
+                echo "try to get PR from commit"
+                COMMIT=` echo "${JSON}" | jq '.event.commits[0].id' | tr -d '"' ` || true
+                if [ -n "${COMMIT}" ]; then
+                    PR_NUMBER=`curl  --retry 10  -s -H "Accept: application/vnd.github.groot-preview+json"  https://api.github.com/repos/${{ github.repository }}/commits/${COMMIT}/pulls | jq -r '.[].number' `
+                else
+                    echo "error, failed to get any commit ID"
+                fi
+                if [ -z "${PR_NUMBER}" ] ; then
+                    PR_NUMBER=` grep -Eio "Merge pull request #[0-9]+ " <<< "${JSON}" | grep -Eo "[0-9]+" | uniq ` || true
+                fi
+                if [ -z "${PR_NUMBER}" ] ; then
+                    echo "error, failed to get PR NUMBER"
+                    exit 1
+                fi
+                #    grep -Ei "https://github.com/.*/commit" <<< "${JSON}"
+                #PR_COMMITS=` grep -Ei "https://github.com/.*/commit" <<< "${JSON}" | awk -F'"' '{print $4}' | uniq -c | awk '{ if ($1 == 1 ) print $2}' | awk -F'/' '{print $NF}' | tr '\n' ' '  `
+                #    grep '"username":'  <<< "${JSON}"
+                #PR_AUTHOR=` grep '"username":' <<< "${JSON}" | awk -F'"' '{print $4}' | sort | uniq  | grep -v "web-flow"  | head -1 | tr -d '\n' `
+                #    [ -n "${PR_AUTHOR}" ] || { echo "no PR_AUTHOR, ignore" ; }
+          #
+          fi
+          RP_API_BODY=` curl  --retry 10  https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER} -s -H "Accept: application/vnd.github.groot-preview+json" `
+          PR_COMMITS=` echo "${RP_API_BODY}" |  jq ' .merge_commit_sha ' | tr -d '"' `
+          PR_AUTHOR=` echo "${RP_API_BODY}" |  jq ' .user.login ' | tr -d '"' `
+          PR_URL="https://github.com/${{ github.repository }}/pull/${PR_NUMBER}"
+          ACTION_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
+          #gh pr view ${PR_NUMBER} || { echo "failed to get pr ${PR_NUMBER}" ; exit 1 ; }
+          #PR_LABEL=` gh pr view ${PR_NUMBER} | grep -i "^labels:" | tr ',' ' ' | tr -s ' ' | sed 's/labels://g' `
+          #    [ -n "${PR_LABEL}" ] || { echo "no PR_LABEL, ignore" ; }
+          PR_LABEL=` echo "${RP_API_BODY}" |  jq ' .labels[].name ' | tr -d '"' | tr '\n' ' ' `
+          #PR_TITLE=`gh pr view ${PR_NUMBER} | sed -n '1 p' `
+          #     [ -n "${PR_TITLE}" ] || { echo "error, no PR_TITLE " ; exit 1 ; }
+          PR_TITLE=` echo "${RP_API_BODY}" |  jq ' .title ' | tr -d '"' `
+          #
+          if [ -z "${PR_COMMITS}" ]; then
+              echo "error, failed to get pr commits"
+          fi
+          echo "number: ${PR_NUMBER}"
+          echo "action url: ${ACTION_URL}"
+          echo "PR_COMMITS: ${PR_COMMITS}"
+          echo "author: ${PR_AUTHOR}"
+          echo "url: ${PR_URL}"
+          echo "PR_LABEL: ${PR_LABEL}"
+          echo "PR_TITLE: ${PR_TITLE}"
+          echo "PR_TITLE=${PR_TITLE}" >> $GITHUB_ENV
+          echo "PR_LABEL=${PR_LABEL}" >> $GITHUB_ENV
+          echo "PR_URL=${PR_URL}" >> $GITHUB_ENV
+          echo "PR_COMMITS=${PR_COMMITS}" >> $GITHUB_ENV
+          echo "PR_AUTHOR=${PR_AUTHOR}" >> $GITHUB_ENV
+          echo "ACTION_URL=${ACTION_URL}" >> $GITHUB_ENV
+          echo "PR_NUMBER=${PR_NUMBER}" >> $GITHUB_ENV
+          echo "=============================== get dest branch from labels ======== "
+          WANT_MERGE_BRANCH_LIST=""
+          if ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.destBranch != '' }}; then
+                WANT_MERGE_BRANCH_LIST=${{ github.event.inputs.destBranch }}
+          else
+                for LABEL in ${PR_LABEL} ; do
+                    echo "checking label $LABEL "
+                    PREFIX="${{ env.PR_LABEL_PREFIX_CHERRYPICK }}"
+                    grep -E "^${PREFIX}" <<< "${LABEL}" &>/dev/null || continue
+                    BRANCH_NAME=` sed 's?'"${PREFIX}"'??' <<< "$LABEL" `
+                    WANT_MERGE_BRANCH_LIST+=" $BRANCH_NAME "
+                done
+          fi
+          [ -z "$WANT_MERGE_BRANCH_LIST" ] && echo "no branch to cherry pick" && exit 0
+          echo "cherry pick to $WANT_MERGE_BRANCH_LIST "
+          #
+          #
+          echo "============ begin to cherry pick ============ "
+          FINAL_FAILURE=false
+          git branch
+          git config user.email "tao.yang@daocloud.io"
+          git config user.name "ty-dc"
+          git config --list
+          gh label create ${{ env.CHERRYPICK_LABEL }} || true
+          for BRANCH in $WANT_MERGE_BRANCH_LIST ; do
+              echo "************** cherry for branch ${BRANCH}"
+              if ! git ls-remote --exit-code --heads origin ${BRANCH} ; then
+                  # todo: create issue
+                  echo "error, branch $BRANCH does not exist"
+                  gh issue create  \
+                      --body "reason: the branch $BRANCH does not exist. PR <${PR_URL}> ,  action <${ACTION_URL}> " \
+                      --title "failed to auto cherry pick PR ${PR_NUMBER} to branch ${BRANCH}" \
+                      --label "${{ env.CHERRYPICK_LABEL }}" \
+                      --assignee "${PR_AUTHOR},${{ env.DEFAULT_REVIEWER }}"
+                  if (($?!=0)) ; then
+                      echo "!!!! error, failed to create issue"
+                      FINAL_FAILURE=true
+                  fi
+                  continue
+              fi
+              git fetch origin ${BRANCH}:${BRANCH} || true
+              git pull origin ${BRANCH}:${BRANCH} || true
+              if ! git checkout ${BRANCH} ; then
+                  echo "error, failed to checkout to branch $BRANCH"
+                  gh issue create  \
+                      --body "reason: failed to get the branch $BRANCH. PR <${PR_URL}> ,  action <${ACTION_URL}> " \
+                      --title "failed to auto cherry pick PR ${PR_NUMBER} to branch ${BRANCH}" \
+                      --label "${{ env.CHERRYPICK_LABEL }}" \
+                      --assignee "${PR_AUTHOR},${{ env.DEFAULT_REVIEWER }}"
+                  if (($?!=0)) ; then
+                      echo "!!!! error, failed to create issue"
+                      FINAL_FAILURE=true
+                  fi
+                  continue
+              fi
+              PR_BRANCH=robot/cherrypick/pr${PR_NUMBER}/${BRANCH}
+              echo "PR_BRANCH=${PR_BRANCH}" >> $GITHUB_ENV
+              echo "BRANCH=${BRANCH}" >> $GITHUB_ENV
+              git branch --show-current
+              FAIL=false
+              UPDATE=false
+              ERROR_MESSAGE=""
+              echo "PR_COMMITS=PR_COMMITS"
+              for COMMIT in $PR_COMMITS; do
+                    if ! ERROR_MESSAGE=`git cherry-pick -m 1 $COMMIT 2>&1` ; then
+                          echo ">>>>>>>>>>>> fail when cherry pick $COMMIT to branch $BRANCH "
+                          echo "$ERROR_MESSAGE"
+                          echo "---- failuire detail"
+                          git status
+                          git diff
+                          echo "<<<<<<<<<<<<<"
+                          if git diff --exit-code --quiet ; then
+                              echo "no changes happen, ignore cherry pick $COMMIT "
+                              git cherry-pick --abort || true
+                              git reset --hard HEAD || true
+                              continue
+                          else
+                              FAIL=true
+                              echo "error, failed to cherry pick $COMMIT "
+                              git cherry-pick --abort || true
+                              git reset --hard HEAD || true
+                              break
+                          fi
+                    else
+                        UPDATE=true
+                        echo "succeed to cherry pick $COMMIT to branch $BRANCH "
+                    fi
+              done
+              echo "FAIL=${FAIL}" >> $GITHUB_ENV
+              echo "UPDATE=${UPDATE}" >> $GITHUB_ENV
+              echo "ERROR_MESSAGE<<EOF" >> $GITHUB_ENV
+              echo "$ERROR_MESSAGE" >> $GITHUB_ENV
+              echo "EOF" >> $GITHUB_ENV
+          done
 
       - uses: crazy-max/ghaction-import-gpg@v5
         with:
@@ -53,27 +206,28 @@ jobs:
 
       - name: Create Pull Request
         id: create_pr
+        if: ${{ env.FAIL != 'true' && env.UPDATE == 'true' }}
         uses: peter-evans/create-pull-request@v5.0.2
         with:
-          title: "test"
-          commit-message: test
-          branch: robot-test
-          delete-branch: false
-          base: release-v0.8
+          title: ${{ env.PR_TITLE }}
+          commit-message: ${{ env.PR_COMMITS }}
           committer: ty-dc <tao.yang@daocloud.io>
+          branch: ${{ env.PR_BRANCH }}
           author: ty-dc <tao.yang@daocloud.io>
+          delete-branch: false
+          base: ${{ env.BRANCH }}
           signoff: true
           token: ${{ steps.generate_token.outputs.token }}
           labels: ${{ env.CHERRYPICK_LABEL }}
-          body: "this is test xxxxxxxxxxx"
-          reviewers: ty-dc
+          body: "robot cherry pick PR <${{ env.PR_URL }}> from <${{ env.PR_AUTHOR }}>,to branch <${{ env.BRANCH }}>,  action <${{ env.ACTION_URL }}>  , commits ${{ env.PR_COMMITS }}"
+          reviewers: ${{ env.PR_AUTHOR }},${{ env.DEFAULT_REVIEWER }}
 
       - name: Creat Issue
         id: create_issue
         if: ${{ env.FAIL == 'true' && env.UPDATE != 'true' }}
         uses: dacbd/create-issue-action@v1.2.1
         with:
-          token: ${{ secrets.WELAN_PAT }}
+          token: ${{ steps.generate_token.outputs.token }}
           title: "failed to cherry pick PR ${{ env.PR_NUMBER }} from ${{ env.PR_AUTHOR }}, to branch ${{ env.BRANCH }}"
           body: |
             commits ${{ env.PR_COMMITS }} of ${{ env.PR_AUTHOR }} conflict when merging to branch ${{ env.BRANCH }}.
@@ -83,10 +237,3 @@ jobs:
             <${{ env.ERROR_MESSAGE }}>
           labels: ${{ env.CHERRYPICK_LABEL }}
           assignees: ${{ env.PR_AUTHOR }},${{ env.DEFAULT_REVIEWER }}
-
-      - name: check result
-        if: ${{ steps.create_pr.result == 'failure' || steps.create_issue.result == 'failure' }}
-        run: |
-              # if failed to create issue or pr, fails
-              echo "error, failuire happened"
-              exit 1
