Update auto-cherrypick.yaml

diff --git a/.github/workflows/auto-cherrypick.yaml b/.github/workflows/auto-cherrypick.yaml
--- a/.github/workflows/auto-cherrypick.yaml
+++ b/.github/workflows/auto-cherrypick.yaml
@@ -30,8 +30,14 @@ jobs:
         with:
           fetch-depth: 0
 
+      - uses: crazy-max/ghaction-import-gpg@v6
+        with:
+          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
+          passphrase: ${{ secrets.GPG_PASSPHRASE }}
+          git_user_signingkey: true
+          git_commit_gpgsign: true
+
       - name: cherry pick
-        id: cherry-pick
         env:
           GITHUB_TOKEN: ${{ secrets.WELAN_PAT }}
           JSON: ${{ toJSON(github) }}
@@ -86,36 +92,35 @@ jobs:
           echo "url: ${PR_URL}"
           echo "PR_LABEL: ${PR_LABEL}"
           echo "PR_TITLE: ${PR_TITLE}"
-          echo "PR_TITLE=${PR_TITLE}" >> $GITHUB_ENV
-          echo "PR_LABEL=${PR_LABEL}" >> $GITHUB_ENV
-          echo "PR_URL=${PR_URL}" >> $GITHUB_ENV
-          echo "PR_COMMITS=${PR_COMMITS}" >> $GITHUB_ENV
-          echo "PR_AUTHOR=${PR_AUTHOR}" >> $GITHUB_ENV
-          echo "ACTION_URL=${ACTION_URL}" >> $GITHUB_ENV
-          echo "PR_NUMBER=${PR_NUMBER}" >> $GITHUB_ENV
+          #
+          #
           echo "=============================== get dest branch from labels ======== "
           WANT_MERGE_BRANCH_LIST=""
+          INITIAL_LABEL=""
           if ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.destBranch != '' }}; then
                 WANT_MERGE_BRANCH_LIST=${{ github.event.inputs.destBranch }}
           else
                 for LABEL in ${PR_LABEL} ; do
                     echo "checking label $LABEL "
                     PREFIX="${{ env.PR_LABEL_PREFIX_CHERRYPICK }}"
-                    grep -E "^${PREFIX}" <<< "${LABEL}" &>/dev/null || continue
+                    if ! grep -E "^${PREFIX}" <<< "${LABEL}" &>/dev/null; then
+                        INITIAL_LABEL+="${LABEL},"
+                        continue
+                    fi
                     BRANCH_NAME=` sed 's?'"${PREFIX}"'??' <<< "$LABEL" `
                     WANT_MERGE_BRANCH_LIST+=" $BRANCH_NAME "
                 done
           fi
           [ -z "$WANT_MERGE_BRANCH_LIST" ] && echo "no branch to cherry pick" && exit 0
           echo "cherry pick to $WANT_MERGE_BRANCH_LIST "
+          echo "INITIAL_LABEL: ${INITIAL_LABEL}"
           #
           #
           echo "============ begin to cherry pick ============ "
           FINAL_FAILURE=false
           git branch
-          git config  user.email "robot@example.com"
+          git config  user.email "tao.yang@daocloud.io"
           git config  user.name "robot"
-          git config --list
           gh label create ${{ env.CHERRYPICK_LABEL }} || true
           for BRANCH in $WANT_MERGE_BRANCH_LIST ; do
               echo "************** cherry for branch ${BRANCH}"
@@ -134,7 +139,6 @@ jobs:
                   continue
               fi
               git fetch origin ${BRANCH}:${BRANCH} || true
-              git pull origin ${BRANCH}:${BRANCH} || true
               if ! git checkout ${BRANCH} ; then
                   echo "error, failed to checkout to branch $BRANCH"
                   gh issue create  \
@@ -149,13 +153,11 @@ jobs:
                   continue
               fi
               PR_BRANCH=robot/cherrypick/pr${PR_NUMBER}/${BRANCH}
-              echo "PR_BRANCH=${PR_BRANCH}" >> $GITHUB_ENV
-              echo "BRANCH=${BRANCH}" >> $GITHUB_ENV
+              git checkout -b ${PR_BRANCH}
               git branch --show-current
               FAIL=false
               UPDATE=false
               ERROR_MESSAGE=""
-              echo "PR_COMMITS=PR_COMMITS"
               for COMMIT in $PR_COMMITS; do
                     if ! ERROR_MESSAGE=`git cherry-pick -m 1 $COMMIT 2>&1` ; then
                           echo ">>>>>>>>>>>> fail when cherry pick $COMMIT to branch $BRANCH "
@@ -181,54 +183,35 @@ jobs:
                         echo "succeed to cherry pick $COMMIT to branch $BRANCH "
                     fi
               done
-              echo "FAIL=${FAIL}" >> $GITHUB_ENV
-              echo "UPDATE=${UPDATE}" >> $GITHUB_ENV
-              echo "ERROR_MESSAGE<<EOF" >> $GITHUB_ENV
-              echo "$ERROR_MESSAGE" >> $GITHUB_ENV
-              echo "EOF" >> $GITHUB_ENV
+              if [ "$FAIL" == "true" ] ; then
+                  echo "failed to cherry pick to branch $BRANCH "
+                  FINAL_FAILURE=true
+                  echo -e "commits $PR_COMMITS of ${PR_AUTHOR} conflict when merging to branch $BRANCH, please manually cherry pick it by yourself. \n PR <${PR_URL}> ,  action <${ACTION_URL}>  \n\n  \`\`\`\n${ERROR_MESSAGE}\n\`\`\` " | \
+                       gh issue create  \
+                        --title "failed to cherry pick PR ${PR_NUMBER} from ${PR_AUTHOR}, to branch ${BRANCH}" \
+                        --label "${{ env.CHERRYPICK_LABEL }}" \
+                        --assignee "${PR_AUTHOR},${{ env.DEFAULT_REVIEWER }}" \
+                        --body-file -
+              fi
+              if [ "$UPDATE" == "true" ] ; then
+                  echo "succeeded to cherry pick to branch $BRANCH "
+                  # create a pr
+                  git commit -s -S --amend --no-edit
+                  git push origin ${PR_BRANCH}:${PR_BRANCH} -f
+                  gh pr create --title "${PR_TITLE}" \
+                      --assignee "${PR_AUTHOR},${{ env.DEFAULT_REVIEWER }}" \
+                      --label ${{ env.CHERRYPICK_LABEL }},${INITIAL_LABEL} \
+                      --body "robot cherry pick PR <${PR_URL}> from ${PR_AUTHOR},to branch ${BRANCH},  action <${ACTION_URL}>  , commits $PR_COMMITS " \
+                      --base ${BRANCH}
+              else
+                  echo "no changes happened for commits $PR_COMMITS, ignore create pr"
+              fi
           done
+          echo "=========== check result ============"
+          if [ "$FINAL_FAILURE" == "true" ] ; then
+              # if failed to create issue or pr, fails
+              echo "error, failuire happened"
+          else
+              echo "all done"
+          fi
 
-      - uses: crazy-max/ghaction-import-gpg@v5
-        with:
-          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
-          passphrase: ${{ secrets.GPG_PASSPHRASE }}
-          git_user_signingkey: true
-          git_commit_gpgsign: true
-
-      - name: Sign commit and push changes
-        run: |
-          git add .
-          git commit -s -S --amend --no-edit
-
-      - name: Create Pull Request
-        id: create_pr
-        if: ${{ env.FAIL != 'true' && env.UPDATE == 'true' }}
-        uses: peter-evans/create-pull-request@v5.0.2
-        with:
-          title: ${{ env.PR_TITLE }}
-          commit-message: ${{ env.PR_COMMITS }}
-          committer: ty-dc <tao.yang@daocloud.io>
-          branch: ${{ env.PR_BRANCH }}
-          delete-branch: false
-          base: ${{ env.BRANCH }}          
-          signoff: true
-          token: ${{ secrets.WELAN_PAT }}
-          labels: ${{ env.CHERRYPICK_LABEL }}
-          body: "robot cherry pick PR <${{ env.PR_URL }}> from <${{ env.PR_AUTHOR }}>,to branch <${{ env.BRANCH }}>,  action <${{ env.ACTION_URL }}>  , commits ${{ env.PR_COMMITS }}"
-          reviewers: ${{ env.PR_AUTHOR }},${{ env.DEFAULT_REVIEWER }}
-
-      - name: Creat Issue
-        id: create_issue
-        if: ${{ env.FAIL == 'true' && env.UPDATE != 'true' }}
-        uses: dacbd/create-issue-action@v1.2.1
-        with:
-          token: ${{ secrets.WELAN_PAT }}
-          title: "failed to cherry pick PR ${{ env.PR_NUMBER }} from ${{ env.PR_AUTHOR }}, to branch ${{ env.BRANCH }}"
-          body: |
-            commits ${{ env.PR_COMMITS }} of ${{ env.PR_AUTHOR }} conflict when merging to branch ${{ env.BRANCH }}.
-            please manually cherry pick it by yourself. 
-            PR <${{ env.PR_URL }}> , action <${{ env.ACTION_URL }}> .
-            error log:
-            <${{ env.ERROR_MESSAGE }}>
-          labels: ${{ env.CHERRYPICK_LABEL }}
-          assignees: ${{ env.PR_AUTHOR }},${{ env.DEFAULT_REVIEWER }}
